-- 影视影评分享系统 - 数据导入SQL (修正版)
-- 字段已对齐 app/models.py 实际定义

-- 分类数据
INSERT INTO category (id, name) VALUES (1, '电影');
INSERT INTO category (id, name) VALUES (2, '电视剧');
INSERT INTO category (id, name) VALUES (3, '综艺');
INSERT INTO category (id, name) VALUES (4, '动漫');

-- 影视数据 (30条)
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('流浪地球2', '1', '/uploads/posters/poster_01.png', '//player.bilibili.com/player.html?bvid=BV1K8411T7ev&page=1&autoplay=0&danmaku=0&high_quality=1', '太阳即将毁灭，人类在地球表面建造了大量推进器，将地球推离太阳系，启程奔向遥远的比邻星。在这一宏大计划实施之前，一场关于人类命运的终极抉择正悄然上演。吴京、刘德华联袂出演，特效震撼，工业水准迈上新台阶，中国科幻的里程碑之作。', '吴京、刘德华、李雪健、沙溢、宁理', '2023-01-22', '8.3', '0', '2026-06-19 10:40:19.345834');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('满江红', '1', '/uploads/posters/poster_02.png', '//player.bilibili.com/player.html?bvid=BV1AR4y1a7kf&page=1&autoplay=0&danmaku=0&high_quality=1', '南宋绍兴年间，岳飞死后四年，秦桧率大队人马准备与金人会谈。一名小兵与神秘女子的相遇，引发了一场惊天谜局。张艺谋导演，悬疑与喜剧完美融合，沈腾、易烊千玺贡献精彩表演，结尾慷慨激昂令人动容。', '沈腾、易烊千玺、张译、雷佳音、岳云鹏', '2023-01-22', '8.0', '0', '2026-06-19 10:40:19.351862');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('你好，李焕英', '1', '/uploads/posters/poster_03.png', '//player.bilibili.com/player.html?bvid=BV1F5411E7o9&page=1&autoplay=0&danmaku=0&high_quality=1', '贾晓玲意外穿越到1981年，与年轻时的母亲李焕英成为好友。她试图改变母亲的命运，让她过上更幸福的生活，却在最后揭开了令人泪崩的真相。贾玲首部导演作品，票房破54亿，是中国影史最卖座的女导演电影。', '贾玲、张小斐、沈腾、陈赫、李焕英', '2021-02-12', '8.2', '0', '2026-06-19 10:40:19.351862');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('长津湖', '1', '/uploads/posters/poster_04.png', '//player.bilibili.com/player.html?epid=350065&autoplay=0&danmaku=0&high_quality=1', '1950年，中国人民志愿军第九兵团奉命入朝参战。在极度严寒的长津湖战役中，志愿军战士以钢铁意志与美军展开殊死搏斗，创造了抗美援朝战争中最为惨烈的战役奇迹。吴京、易烊千玺主演，三位导演联合执导，史诗战争巨制。', '吴京、易烊千玺、朱亚文、李晨、胡军', '2021-09-30', '7.9', '0', '2026-06-19 10:40:19.353580');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('封神第一部：朝歌风云', '1', '/uploads/posters/poster_05.png', '//player.bilibili.com/player.html?bvid=BV1bp4y1A7Ww&page=1&autoplay=0&danmaku=0&high_quality=1', '商王殷寿勾连狐妖妲己，暴虐无道；西伯侯之子姬发受命于天，踏上斩神封神之路。乌尔善导演历时8年打造的奇幻史诗，视觉震撼，费翔饰演的殷寿惊艳全场，中国神话世界观构建宏大。', '费翔、于适、妮露、李雪健、黄渤', '2023-07-20', '7.8', '0', '2026-06-19 10:40:19.354973');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('消失的她', '1', '/uploads/posters/poster_06.png', '//player.bilibili.com/player.html?bvid=BV1zc411u7aS&page=1&autoplay=0&danmaku=0&high_quality=1', '何非在海岛旅游途中声称妻子李木子失踪，警察介入调查，一个女性深陷婚姻谎局的惊天秘密逐渐浮出水面。朱一龙、倪妮主演，改编自苏联电影《镜中人》，悬疑反转不断，引发广泛社会讨论。', '朱一龙、倪妮、文咏珊、李现', '2023-06-22', '7.0', '0', '2026-06-19 10:40:19.355479');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('奥本海默', '1', '/uploads/posters/poster_07.png', '//player.bilibili.com/player.html?bvid=BV1oh4y1J7MH&page=1&autoplay=0&danmaku=0&high_quality=1', '原子弹之父J·罗伯特·奥本海默在二战期间主导【曼哈顿计划】，研发出改变世界格局的核武器，却在战后因政治迫害而遭受审判。克里斯托弗·诺兰导演，基里安·墨菲奉献生涯最佳演出，荣获第96届奥斯卡最佳影片等七项大奖。', '基里安·墨菲、艾米莉·布朗特、马特·达蒙、小罗伯特·唐尼', '2023-08-30', '8.9', '0', '2026-06-19 10:40:19.356721');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('星际穿越', '1', '/uploads/posters/poster_08.png', '//player.bilibili.com/player.html?bvid=BV1P5411o7pU&page=1&autoplay=0&danmaku=0&high_quality=1', '地球面临粮食危机，前宇航员库珀受命穿越虫洞，前往另一个星系寻找人类新家园。在宇宙深处，时间以不同速度流逝，父女之间跨越时空的羁绊令人动容。诺兰执导的科幻神作，迄今为止最震撼的太空视觉体验之一。', '马修·麦康纳、安妮·海瑟薇、杰西卡·查斯坦、迈克尔·凯恩', '2014-11-12', '9.3', '0', '2026-06-19 10:40:19.358232');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('肖申克的救赎', '1', '/uploads/posters/poster_09.png', '//player.bilibili.com/player.html?bvid=BV1Zt411P72D&page=1&autoplay=0&danmaku=0&high_quality=1', '银行家安迪·杜弗雷因被误判谋杀妻子及其情人入狱，在肖申克监狱结识了囚犯瑞德，两人建立了深厚友谊。安迪用近二十年时间实现了一个关于自由的伟大逃脱计划。豆瓣电影Top1，人类电影史上最伟大的作品之一。', '蒂姆·罗宾斯、摩根·弗里曼', '1994-09-23', '9.7', '0', '2026-06-19 10:40:19.358232');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('熊出没·伴我熊芯', '1', '/uploads/posters/poster_10.png', '//player.bilibili.com/player.html?bvid=BV1mY41197Q4&page=1&autoplay=0&danmaku=0&high_quality=1', '光头强为了拯救患病的熊大，踏上了寻找【熊芯】的冒险旅程。然而旅途中他们发现了一个惊天秘密——一切的背后，都指向一段尘封已久的记忆。年度最催泪合家欢动画电影，让无数成年人在影院泪目。', '配音：张伟、潘霜霜、辛鹏', '2023-01-22', '8.0', '0', '2026-06-19 10:40:19.360413');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('狂飙', '2', '/uploads/posters/poster_11.png', '//player.bilibili.com/player.html?bvid=BV1gv4y1i7iQ&page=1&autoplay=0&danmaku=0&high_quality=1', '1990年代至2021年，警察安欣与绰号黑老大的高启强三十年的命运纠葛。从弱小鱼贩到一方枭雄，高启强走过了一条无法回头的罪恶之路。张译、张颂文双雄对决，张颂文的表演令人叹服，成为2023年现象级国剧。', '张译、张颂文、李一桐、倪大红、韩童生', '2023-01-14', '9.0', '0', '2026-06-19 10:40:19.362909');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('繁花', '2', '/uploads/posters/poster_12.png', '//player.bilibili.com/player.html?bvid=BV1ma4y167BU&page=1&autoplay=0&danmaku=0&high_quality=1', '1990年代的上海，阿宝、沪生、小毛三个年轻人在时代浪潮中追逐梦想、经历爱情与友情的跌宕起伏。王家卫首部电视剧作品，胡歌、唐嫣等强阵容，唯美影像风格令人沉醉，展现魔都旧日繁华。', '胡歌、唐嫣、马伊琍、辛芷蕾、游本昌', '2023-12-27', '8.0', '0', '2026-06-19 10:40:19.362909');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('庆余年 第二季', '2', '/uploads/posters/poster_13.png', '//player.bilibili.com/player.html?bvid=BV1x94y1L7ZC&page=1&autoplay=0&danmaku=0&high_quality=1', '范闲在庆国朝堂上历经重重险阻，与太子、二皇子斗智斗勇，逐渐揭开母亲叶轻眉的身世之谜与庆帝的惊天秘密。时隔五年续集回归，张若昀、李沁再度出演，王启年、范思辙等配角依旧抢眼。', '张若昀、李沁、陈道明、吴刚、田雨', '2024-05-16', '8.3', '0', '2026-06-19 10:40:19.363955');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('甄嬛传', '2', '/uploads/posters/poster_14.png', '//player.bilibili.com/player.html?bvid=BV16a4y1U73F&page=1&autoplay=0&danmaku=0&high_quality=1', '雍正年间，少女甄嬛因貌美入选后宫，从天真懵懂逐渐成长为深谙宫廷权谋的熹贵妃，一生都在权力与情感的漩涡中挣扎。孙俪奉献教科书级表演，台词精彩，人物塑造层次丰富，被誉为中国宫廷剧巅峰之作，全球累计播放量超百亿。', '孙俪、陈建斌、蔡少芬、刘雪华、斓曦', '2011-11-17', '9.4', '0', '2026-06-19 10:40:19.364978');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('白夜追凶', '2', '/uploads/posters/poster_15.png', '//player.bilibili.com/player.html?bvid=BV1gz4y1Q7fb&page=1&autoplay=0&danmaku=0&high_quality=1', '刑警队长关宏峰与弟弟关宏宇，一个只能在白天行动，一个只能在夜晚出没，两兄弟联手追查连环杀人案，同时试图证明弟弟的清白。潘粤明一人分饰两角，被誉为中国悬疑推理网剧的天花板，公安部推荐优秀作品。', '潘粤明、王龙正、陈创、林嘉欣', '2017-08-01', '9.0', '0', '2026-06-19 10:40:19.364978');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('人世间', '2', '/uploads/posters/poster_16.png', '//player.bilibili.com/player.html?bvid=BV1Yh411J7HG&page=1&autoplay=0&danmaku=0&high_quality=1', '从1969年至今，跨越五十年，吉春市光字片胡同里，普通工人家庭周氏三兄妹各自坎坷又充实的人生故事。雷佳音、辛柏青、宋佳、殷桃主演，改编自茅盾文学奖同名小说，展现中国社会五十年变迁，感动无数观众。', '雷佳音、辛柏青、宋佳、殷桃、丁勇岱', '2022-01-28', '8.8', '0', '2026-06-19 10:40:19.365979');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('请回答1988', '2', '/uploads/posters/poster_17.png', '//player.bilibili.com/player.html?bvid=BV1ps411277A&page=1&autoplay=0&danmaku=0&high_quality=1', '1988年首尔双门洞胡同里，五个相邻家庭的孩子们一起长大，经历爱情、友谊、告别与成长。温暖治愈的生活流叙事，引发几代观众的青春共鸣。豆瓣9.7分，被誉为韩剧史上最伟大的作品。', '李惠利、朴宝剑、柳俊烈、高庚杓、崔成元', '2015-11-06', '9.7', '0', '2026-06-19 10:40:19.367479');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('风吹半夏', '2', '/uploads/posters/poster_18.png', '//player.bilibili.com/player.html?bvid=BV1W8411D7Cn&page=1&autoplay=0&danmaku=0&high_quality=1', '1990年代，许半夏凭借机敏与胆识从废品收购起步，在废钢行业一路打拼成为商界女强人。赵丽颖、欧阳智薛主演，展现时代浪潮中女性的成长与蜕变，商战情节紧凑，人物弧光完整动人。', '赵丽颖、欧阳智薛、李光洁', '2022-11-28', '8.4', '0', '2026-06-19 10:40:19.368481');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('歌手2024', '3', '/uploads/posters/poster_19.png', '//player.bilibili.com/player.html?bvid=BV1Sx4y1b7Zv&page=1&autoplay=0&danmaku=0&high_quality=1', '湖南卫视王牌音乐竞演节目回归，那英领衔中国歌手出战，与来自海外的顶尖歌手同台竞技。节目以直播形式播出，那英与KZ Tandingan等人的对决引发全网热议，"中国人不是随随便便的"成为年度名言。', '那英、汪苏泷、法老、海来阿木', '2024-05-10', '7.8', '0', '2026-06-19 10:40:19.370035');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('向往的生活', '3', '/uploads/posters/poster_20.png', '//player.bilibili.com/player.html?bvid=BV1nX4y1B7RL&page=1&autoplay=0&danmaku=0&high_quality=1', '何炅、黄磊、彭昱畅在远离城市喧嚣的蘑菇屋，过一段慢节奏的田园生活。邀请嘉宾前来做客，一起种菜、做饭、聊天。最治愈的慢综艺，让人在快节奏的生活中感受到宁静与温暖。', '何炅、黄磊、彭昱畅、张子枫', '2017-05-12', '8.6', '0', '2026-06-19 10:40:19.371374');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('极限挑战', '3', '/uploads/posters/poster_21.png', '//player.bilibili.com/player.html?bvid=BV1rt411w7qz&page=1&autoplay=0&danmaku=0&high_quality=1', '孙红雷、黄渤、罗志祥、王迅、张艺兴、黄磊六位男演员，化身极限男人帮，在全国各地接受各种极限挑战任务。每期节目暗藏社会议题，笑中有泪，曾被誉为综艺天花板，引发强烈共情。', '孙红雷、黄渤、罗志祥、王迅、张艺兴、黄磊', '2015-06-14', '9.0', '0', '2026-06-19 10:40:19.372771');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('乘风破浪的姐姐', '3', '/uploads/posters/poster_22.png', '//player.bilibili.com/player.html?bvid=BV1Nm4y1y7W3&page=1&autoplay=0&danmaku=0&high_quality=1', '30位平均年龄30+的女星，重新登上舞台，展现女性力量与魅力。宁静一句"你们不要惹我"出圈，张雨绮、万茜等各展风采。节目引发社会对女性年龄与价值的广泛讨论，成为破圈的现象级综艺。', '宁静、张雨绮、万茜、郁可唯、伊能静', '2020-06-12', '8.0', '0', '2026-06-19 10:40:19.373780');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('奔跑吧', '3', '/uploads/posters/poster_23.png', '//player.bilibili.com/player.html?bvid=BV1ks411274v&page=1&autoplay=0&danmaku=0&high_quality=1', '改编自韩国综艺《Running Man》的户外竞技真人秀，邓超、李晨、陈赫、Angelababy等人每期接受各种趣味挑战。搞笑与真情并存，多个经典名场面深入人心，是中国综艺史上长寿的常青树节目之一。', '邓超、李晨、陈赫、郑恺、迪丽热巴', '2014-10-10', '7.5', '0', '2026-06-19 10:40:19.374781');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('王牌对王牌', '3', '/uploads/posters/poster_24.png', '//player.bilibili.com/player.html?bvid=BV177411e7MJ&page=1&autoplay=0&danmaku=0&high_quality=1', '沈腾、贾玲、华晨宇、关晓彤四位固定嘉宾，每期邀请不同主题的嘉宾团进行各种趣味竞技。沈腾与贾玲的搭档堪称综艺史上最强喜剧cp，每期节目都能带来意想不到的爆笑时刻。', '沈腾、贾玲、华晨宇、关晓彤', '2016-02-14', '8.2', '0', '2026-06-19 10:40:19.375959');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('哪吒之魔童降世', '4', '/uploads/posters/poster_25.png', '//player.bilibili.com/player.html?bvid=BV1ot411c7LV&page=1&autoplay=0&danmaku=0&high_quality=1', '天地灵气孕育出一颗混元珠，元始天尊将其分为灵珠和魔丸。阴差阳错，本该是灵珠转世的哪吒，却成了魔丸降生。"我命由我不由天"——这个生来被众人嫌弃的孩子，用行动证明了命运由自己掌握。国漫里程碑，票房破50亿。', '配音：吕艳婷、囧森瑟夫、唐小喜', '2019-07-26', '9.0', '0', '2026-06-19 10:40:19.380246');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('进击的巨人', '4', '/uploads/posters/poster_26.png', '//player.bilibili.com/player.html?bvid=BV1Va4y1v7yf&page=1&autoplay=0&danmaku=0&high_quality=1', '人类被迫居住在高墙之内，以抵挡巨人的侵食。少年艾伦·耶格尔目睹母亲被巨人吞噬，发誓要消灭世上所有的巨人。随着秘密逐渐揭开，真正的敌人远比巨人更为复杂。被誉为神作的史诗级动漫。', '配音：梶裕贵、石川由依、井上麻里奈', '2013-04-07', '9.6', '0', '2026-06-19 10:40:19.381251');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('鬼灭之刃', '4', '/uploads/posters/poster_27.png', '//player.bilibili.com/player.html?epid=430726&autoplay=0&danmaku=0&high_quality=1', '大正时代，炭治郎的家人惨遭鬼灭，妹妹禰豆子变成了鬼。为了让妹妹变回人类，炭治郎加入鬼杀队，踏上了斩鬼之路。「无限列车篇」打破日本票房纪录，"煉獄杏寿郎"成为动漫史上最深入人心的角色之一。', '配音：花江夏树、鬼头明里、下野纮', '2019-04-06', '8.9', '0', '2026-06-19 10:40:19.382254');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('灌篮高手（剧场版）', '4', '/uploads/posters/poster_28.png', '//player.bilibili.com/player.html?bvid=BV1pN4y1u7Ao&page=1&autoplay=0&danmaku=0&high_quality=1', '以流川枫、樱木花道、赤木刚宪等人为主角的青春热血高中篮球故事，2022年剧场版将目光聚焦在宫城良田身上，描述他与哥哥之间的羁绊与热爱篮球的初心。井上雄彦亲自执导，令一代人的青春记忆再度燃烧。', '配音：仲村宗悟、神尾晋一郎、三宅健太', '2022-11-04', '9.0', '0', '2026-06-19 10:40:19.386036');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('火影忍者', '4', '/uploads/posters/poster_29.png', '//player.bilibili.com/player.html?bvid=BV1pFkCBhEEN&page=1&autoplay=0&danmaku=0&high_quality=1', '体内封印着九尾妖狐的少年漩涡鸣人，从被全村嫌弃的孤独少年，一步一步成长为守护整个忍界的英雄。友情、梦想、牺牲……每一个经典场景都让无数人热泪盈眶。影响了一整代动漫迷的青春，影分身之术无人不知。', '配音：竹内顺子、井上和彦、中村千绘', '2002-10-03', '9.0', '1', '2026-06-19 10:40:19.387048');
INSERT INTO movie (title, category_id, poster_url, trailer_url, intro, actors, release_date, rating, likes, created_at) VALUES ('名侦探柯南', '4', '/uploads/posters/poster_30.png', '//player.bilibili.com/player.html?bvid=BV1Cx411Z7Ys&page=1&autoplay=0&danmaku=0&high_quality=1', '高中生侦探工藤新一被黑衣组织灌下毒药后，身体缩小变成小学生，化名江户川柯南，隐藏在小兰身边继续追查组织踪迹。每年一部剧场版，始终保持高水准，是日本国民级推理动漫，也是童年的共同记忆。', '配音：高山南、山崎和佳奈、神谷明', '1996-01-08', '9.1', '0', '2026-06-19 10:40:19.389597');